application: lipid-converter
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
 - name: django
   version: "latest"
 - name: numpy
   version: "latest"

builtins:
 - deferred: on

handlers:
 - url: /static
   static_dir: static
   expiration: '0'

 - url: /.*
   script: convert.main.application

